platform :ios, '10.0'

target 'TheSwiftProject' do
	use_frameworks!

	pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'HandyJSON', '~>4.0.0-beta.1'
    pod 'Kingfisher'
    pod 'IBAnimatable'
    pod 'SwiftTheme'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SQLite.swift'
    pod 'SVProgressHUD'
    pod 'MJRefresh'
    pod 'FDFullscreenPopGesture'
    pod 'SGPagingView'
    pod 'BMPlayer'

end

